### ISSUE TITLE
Footer text update - copyright year

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#89]
## Description
The year is old now--it shows 2016, and not 2018.

Let's [display the current year using JavaScript](https://www.tutorialspoint.com/javascript/date_getyear.htm)? If you have a different or better idea, let me know.

![screen shot 2018-07-05 at 1 55 31 pm](https://user-images.githubusercontent.com/13045020/42339516-2df00986-805b-11e8-83d1-ee13ffdfdee4.png)

**Comment by bciar** [comment]
### **Great idea!**

**Comment by joeflack4** [comment]
Why thank you!

Checked and looks good to me.
