### ISSUE TITLE
Distribution indicators (pie chart / "method mix" indicators) not displaying due to "None"

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/datalab#99]
## Description
@bciar I do not know the best strategy for to fix this. But basically the problem is that... (1) we have changed the characteristic (break data down by...) list to select "None" by default, and (2) the "distribution indicators" need a characteristic to be selected. Because of (1) and (2), the "distribution indicators" will always be grey / non-selectable by default.

## Screenshots
1. When "None" is selected
![noneselected1](https://user-images.githubusercontent.com/13045020/42458016-fa3bb9c8-8366-11e8-98f0-62981df69403.png)
![noneselected2](https://user-images.githubusercontent.com/13045020/42458015-fa224222-8366-11e8-8af2-52a894825d74.png)

2. When "None" is not selected
![nonenotselected1](https://user-images.githubusercontent.com/13045020/42458014-fa141b0c-8366-11e8-9078-95cc011a6503.png)
![nonenotselected2](https://user-images.githubusercontent.com/13045020/42458013-fa081870-8366-11e8-8266-28cf4016b95e.png)

## What we should do
I think this is bad design; but I do not know what is the best fix. Maybe one of these choices?
a. Change the API
b. Add logic to Datalab: i. If "None" is selected, then the "distribution indicators" should _always_ be selectable, ii. If "None" is selected and then a "distribution indicator" is selected, the Datalab should automatically de-select the characteristic (break data down by...) list; it should change to "Select option".

@bciar What do you think?
@jkpr Adding you in here so that you can participate in the discussion. At our last Datalab meeting, Blake asked if we could have "None" selected by default. However, that is causing this issue as a side effect.

**Comment by jkpr** [comment]
The datalab should not look for "none" and make it the default. The API
should indicate what the default selection is and then the datalab
"pre-selects" that for the user.

**Comment by joeflack4** [comment]
That sounds like a more elegant solution. But if we implement as such, we may still have the issue as described here. Lets follow up more over Slack text / voice.

**Comment by joeflack4** [comment]
@bciar Hey Bciar. Thank you for picking and implementing a solution! I tried it, and one of my attempts worked great!

One of my attempts however did not work. Here is what happened:

1. Start
![1 - start](https://user-images.githubusercontent.com/13045020/43010176-c337627e-8c0d-11e8-8f77-f131eb0248c7.png)

2. I selected one of the "distribution" indicators.
![2 - select distribution indicator](https://user-images.githubusercontent.com/13045020/43010177-c3486aa6-8c0d-11e8-9a4b-a5c75dcbd23a.png)

3. This is my screen after selecting the indicator.
![3 - select distribution indicator after](https://user-images.githubusercontent.com/13045020/43010178-c357046c-8c0d-11e8-8872-b30da87f998d.png)

4. I selected pie chart.
![4 - select pie](https://user-images.githubusercontent.com/13045020/43010179-c3621e4c-8c0d-11e8-91c2-366c453768d7.png)

5. I tried to select a country. But all of the countries are not selectable, because there is no country that will give data for the "distribution" indicator with the "None" type. So then I clicked  outside of the modal to close it.
![5 - try to select country and close modal by clicking outside](https://user-images.githubusercontent.com/13045020/43010180-c36f06e8-8c0d-11e8-93b7-38a790d64db9.png)

6. I closed the modal by clicking outside. But the "indicator" and "break data down by..." menus changed. I was surprised.
![6 - unexpected selections](https://user-images.githubusercontent.com/13045020/43010181-c37f5e9e-8c0d-11e8-8c4d-3cbd7f65e728.png)

7. My "distribution" indicator is not selected. It changed. Now the first indicator in the list is selected.
![7 - unexpected selection of first indicator in list - this is bad](https://user-images.githubusercontent.com/13045020/43010182-c38c9136-8c0d-11e8-96f0-79db386401a4.png)

8. Also, the "beak data down by..." menu changed. However, I think this change is not bad. It automatically selected the only option that can be selected with my distribution indicator.
![8 - unexpected selection of the correct characteristic for the distribution indicator i had previously selected - this is good](https://user-images.githubusercontent.com/13045020/43010183-c39ae52e-8c0d-11e8-80a2-7f7b47a240f0.png)

---

I think there are two problems. Can you review these problems and tell me if my solutions are ok?

#### 1. Problem 1 (screenshot 6)
If I click outside the modal, my selections change. This is a bug.

**My solution**: Fix this. Selections should not change when clicking outside the modal.

#### 2. Problem 2 (screenshot 5)
The countries are not selectable. This is **not** a bug. But this is bad UX. The **real** problem is the API. I think James & I should change some things about distribution indicators. However, I don't know when I will fix the API, so please see my solution for now.

**My solution: ** Can you change so that after clicking a "distribution" indicator, Datalab will automatically select the correct characteristic ("break data down by..."). It should be like this:

##### _[indicator] ---> [characteristic]_
- Contraceptive method mix (all women) ---> Method type(all methods)
- Contraceptive method mix (married women) ---> Method type(all methods)
- Modern contraceptive method mix (all women) ---> Method type(modern methods)
- Modern contraceptive method mix (married women) ---> Method type(modern methods)
- Contraceptive method mix including non-users (all women) ---> Method type(including non-users)
- Contraceptive method mix including non-users (married women) ---> Method type(including non-users)

**Comment by joeflack4** [comment]
The issue from my last comment is fixed now. Also, clicking outside the modal to close it is not possible anymore. The user must click "Done". I am OK with this.

However there is a new issue. If the user selects a "distribution" indicator, then opens up the country-round modal, none of the countries can be selected.

I was able to get around the issue by closing the modal and opening again.

**1. Start**
![1 start](https://user-images.githubusercontent.com/13045020/43100035-0ea4cf7c-8e92-11e8-9c1c-a5fbd5ca6cbf.png)

**2. Select a distribution indicator**
![2 distribution indicator](https://user-images.githubusercontent.com/13045020/43100034-0e94b68c-8e92-11e8-8da0-e29a514059bc.png)

**3. Open country-round modal, but everything is disabled**
![3 disabled county-rounds](https://user-images.githubusercontent.com/13045020/43100033-0e7e91ea-8e92-11e8-92a2-141bf4204139.png)

**4. Click "Done" to close modal, and there is an API call to fetch data**
![4 - data fetching](https://user-images.githubusercontent.com/13045020/43100032-0e70d5e6-8e92-11e8-869a-023cf7a176c6.png)

**5. After closing the modal**
![5 - after closing country-round modal](https://user-images.githubusercontent.com/13045020/43100030-0e523f82-8e92-11e8-98ff-ca32ea7b54f1.png)

**6. After opening modal again, things are now selectable**
![6 -opening country-round modal again](https://user-images.githubusercontent.com/13045020/43100031-0e6144e6-8e92-11e8-8e6e-318341ab565c.png)

**Comment by joeflack4** [comment]
@bciar Looks good!
